name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          path: src

      - name: Setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Pack
        run: |
          mv ./src/pack.py ./pack.py
          python pack.py
          VERSION=$(python -c "print(__import__('info').version)")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          mkdir ./dist
          cd ./output
          zip -r ../dist/Create-Applied-Machine-$VERSION.zip ./*

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Create-Applied-Machine-${{ env.VERSION }}
          path: ./output

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref_type == 'tag'
        with:
          tag_name: ${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: |
            已更新至 `v${{ env.VERSION }}`
          files: |
            dist/*
